### ISSUE TITLE
hi i don't know why my website is loser ? 

### ISSUE THREAD

**Issue by marooj** [bustabit/bustabit-client#103]
How to fix it http://27.102.70.169 ?

please help me i am just remove bits and change it to KRW in my website 1bit=1KRW but i can't understand about why my website is loser ?
i am remove decimal point in website
for example 5.52 bits = 5 bits but in database saved 5.52

**Comment by marooj** [comment]
you can say me how to difficulty game ?

**Comment by RHavar** [comment]
Hi there,
This is the wrong repo. You'll need to comment there or talk to FuzzyHobbit =)
