### ISSUE TITLE
Cache expiration

### ISSUE THREAD

**Issue by Ghrisp** [bustabit/bustabit-client#45]
You didn't specify cache expiration times. Is that intentional?

User@ bustabit: Ghris

**Comment by RHavar** [comment]
Yeah, all the files should have hashes in their names -- so they should never expire. So it's intentional that browser permacache it, because same file name = same file.

**Comment by Ghrisp** [comment]
Not really familiar with this, but some browsers might not accept files being cached if they are permacached. But I could be wrong.

**Comment by RHavar** [comment]
I just tested on my browser, and it's not perfectly ideal  (it's still making a request with etags) but it's getting cached fine (at least me with chrome). More importantly, it's just a really really simple webserver using: https://github.com/mars/create-react-app-buildpack

But when I move to production I won't be using heroku and will have a pretty different webserver and will make sure it has better cache headers there
