### ISSUE TITLE
Cannot fuse valor and silver

### ISSUE THREAD

**Issue by on247** [bustabit/bustabit-client#46]
Expected to get bits , instead i get:
![image](https://cloud.githubusercontent.com/assets/5596081/23442926/4b47c71e-fdf1-11e6-9f5c-bae8c36ac046.png)
Console:

Also look at the formating issue , when i clicked max i got a value with no decimal in the Amount field. ie 100 times actual max

**Comment by RHavar** [comment]
Thanks, fixed
