### ISSUE TITLE
Notifications Get Stuck?

### ISSUE THREAD

**Issue by Overstanding** [bustabit/bustabit-client#54]
Whenever one of these "notifications" pop up for me, It never goes away on it's own...

https://gyazo.com/50d99f44465d1c1b85c03800ad8b401b

I'm not sure if that is intended. I assume you would want it to fade away after 5-10 seconds.

**Comment by joey471** [comment]
They get dismissed after 4 seconds. 
I will change it to 3 seconds.
Please confirm if this works for you. Else, what browser are you using?

**Comment by Overstanding** [comment]
Yes it's much better now from what I can see.

Thank you for the fix!
