### ISSUE TITLE
Sort GAME INFORMATION table by highest cashout

### ISSUE THREAD

**Issue by bustapaladin** [bustabit/bustabit-client#56]
user9x	17	1.9x	15.29	
user15x	387	-	-387	
user8x	280	1.08x	22.40	
user1x	752	1.27x	203.04	
user10x	32	2.15x	36.79	
user0x	552	-	-552	
user4x	260	1.33x	85.80	
Paladinx	50,000	9.52x	426,000	
user17x	157	1.61x	95.77	
user6x	307	1.4x	122.79	
user14x	944	1.17x	160.47	
Vincentx	400	-	-400	

Paladin should be above

**Comment by RHavar** [comment]
Should be done
