### ISSUE TITLE
Remove x out of player name in game information table

### ISSUE THREAD

**Issue by bustapaladin** [bustabit/bustabit-client#57]
user9**x**		
user15**x**	
user8**x**
user1x	752	1.27x	203.04	
user10x	32	2.15x	36.79	
user0x	552	-	-552	
user4x	260	1.33x	85.80	
Paladinx	50,000	9.52x	426,000	
user17x	157	1.61x	95.77	
user6x	307	1.4x	122.79	
user14x	944	1.17x	160.47	
Vincentx	400	-	-400	

The only x should be the 3rd table

**Comment by RHavar** [comment]
Not sure how I didn't notice this. Thanks, fixed with: b8bfb1b65b08c334e1c506261f62fdb20fb68aa9
