### ISSUE TITLE
Fix max cashout profit value in GAME INFORMATION

### ISSUE THREAD

**Issue by bustapaladin** [bustabit/bustabit-client#58]
PLAYER	BET	CASHED OUT	PROFIT	
user5x	612	1.8x	489.60	
user17x	213	1.48x	102.24	
user8x	261	1.15x	39.14	
# Paladinx	60,000	-	-60,000	
user10x	546	1.4x	218.39	
user15x	427	1.01x	4.27	
user9x	716	6.5x	3,938	
user1x	399	11.21x	4,073.79	
user6x	472	2.57x	741.03	
user0x	538	1.02x	10.76	
**# testsx	60,000	-	-60,000**	
user14x	294	2.31x	385.14

ID #6432
BUSTED AT: 91.61x

DATE: Wed, 01 Mar 2017 13:11:11 GMT2 minutes ago

Forced

**Comment by RHavar** [comment]
Fixed with 5d2b6ac3b496a0290af9e6e75fa66efdeff9ebde
