### ISSUE TITLE
Password issues

### ISSUE THREAD

**Issue by kolloh** [bustabit/bustabit-client#62]
I created an account with a password but when I attempt to change the account password or login again, the password indicates it is incorrect.

Also the change password field doesn't allow you to input your own password and only allows pregenerated ones.

**Comment by RHavar** [comment]
Only allowing pre-generated passwords is by-design.  I've had too many bad experiences with users being allowed to pick their own passwords (almost always they reuse something that can be found from a site like leaksource).

I'll take a look at the not being able to use the password, that's a bit strange hasn't happened to me yet

**Comment by kolloh** [comment]
I thought I was able to supply my own password during registration but maybe I wasn't and this is why the password wasn't working as I was using a different one.

If you are only allow pregenerated passwords, I'd like to see a few extra characters in the passwords if possible or at least allow the user to generate a longer password if they wish to.
