### ISSUE TITLE
Processing all queued withdraws returns insuficent balance error even though there is enough balance

### ISSUE THREAD

**Issue by DarkStarFTW** [bustabit/bustabit-client#63]
Basically the title. See the gif:

http://i.imgur.com/5nSSjw5.gifv

**Comment by DarkStarFTW** [comment]
Could be a visual error. Processing all withdraws actually costs 200 bits, and not the 100 bits that is said on the page.

**Comment by RHavar** [comment]
All the withdrawal issues should now be fixed (i hope)
