### ISSUE TITLE
Cashout by autocashout doesn't show up in game history

### ISSUE THREAD

**Issue by DarkStarFTW** [bustabit/bustabit-client#67]
In game #2624, I bet 50k bits with auto cashout at 10x. The game history shows this:
http://i.imgur.com/cwd7sNg.png

(crash at 11.34x, I lost 50k bits)

However, my stats show a 10x win, and I did get the balance from the win.

http://i.imgur.com/dSl40CO.png

**Comment by RHavar** [comment]
Should be fixed by 5d2b6ac3b496a, please reopen if there's still issues
