### ISSUE TITLE
Dillution fee also at DIvesting?

### ISSUE THREAD

**Issue by Ghrisp** [bustabit/bustabit-client#72]
Does divesting also cost fees? I divested 30 million bits and got back the following:

2017-03-05T05:47:02.655434Z	Removed	-23,967,861.47 bits

**Comment by RHavar** [comment]
Nope, but you should've got the difference as "silver". That's because that should be profit, and you can fuse the silver with valor to make bits, or trade with it

**Comment by RHavar** [comment]
The server now has much better logging of all invest/divestment events, and I've reset the database. Now if a weird thing happens again, let me know and i'll be able to audit it all
