### ISSUE TITLE
Visual suggestion for Investing In Bankroll

### ISSUE THREAD

**Issue by Overstanding** [bustabit/bustabit-client#91]
Right now, it lets you try to take out all of your investments, even if you have nothing invested in the house. 

Here's a GIF of what I mean: https://gyazo.com/baf9a8affde7151bc9193bf754770fa1

I think it should look just like the "ADD ALL" button looks when you have 0 bits.

Here's a GIF of what i mean, I have 0 bits when I try doing this:

https://gyazo.com/d250cddf37e11dc2e3655d154835cad5

So if changed to what I'm suggesting, it would be just like the "ADD ALL" button when you have nothing to remove from the investments.

Just another minor polish for V2 :P

**Comment by RHavar** [comment]
I've totally removed the add/remove from the bankroll thingy, so it's a bit improved (i hope), so closing this issue for now
