### ISSUE TITLE
Insurance

### ISSUE THREAD

**Issue by XboxModa** [bustabit/bustabit-client#95]
I don't know if this a good idea or not but I think it would be great if you insurance like if you were betting 200k on 2x the insurance should be 50k but if you lose you get back the 200k but you spend 50k but if they win they get the 200k but you get 50k out of it ect

**Comment by RHavar** [comment]
It's a good idea, but a bit out of scope for the initial release and I'm pretty hesitant to add stuff that would increase the complexity of the game. I'm going to close for now, and revisit when it's in a bit of a more mature state
